"""
Django settings for trainer_monitoring project.

Generated by 'django-admin startproject' using Django 4.2.26.
"""

from pathlib import Path

# ---------------------------
# Basic settings
# ---------------------------
BASE_DIR = Path(__file__).resolve().parent.parent
AUTH_USER_MODEL = "core.User"

SECRET_KEY = 'django-insecure-c)7)qrau47xf1u-$$s-spnus=cx=2$z8^lt7b5z^*d@s7bg&^4'
DEBUG = True
ALLOWED_HOSTS = ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = [
    'http://13.235.132.174:8000',
]

LOGIN_REDIRECT_URL = 'training:trainer_dashboard'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'training:trainer_dashboard'

#LOGIN_URL = 'login'
#LOGOUT_REDIRECT_URL = 'login'
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False
# ---------------------------
# Static files
# ---------------------------
STATIC_URL = '/static/'

# Folder where collectstatic will gather all static files (for production)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Additional static folders for development
STATICFILES_DIRS = [
    BASE_DIR / "core" / "static",  # make sure this folder exists
]

# ---------------------------
# Application definition
# ---------------------------
JAZZMIN_SETTINGS = {
    "site_title": "Trainer Monitoring",
    "site_header": "Trainer Monitoring Admin",
    "site_brand": "Trainer Admin",

    "welcome_sign": "Welcome Admin",

    # 🔥 FORCE readable theme
    "theme": "flatly",
    "dark_mode_theme": None,

    "show_sidebar": True,
    "navigation_expanded": True,

    # Disable theme switch
    "show_ui_builder": False,
}

JAZZMIN_SETTINGS["custom_css"] = "core/admin_fix.css"




INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'training',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'trainer_monitoring.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'trainer_monitoring.wsgi.application'

# ---------------------------
# Database
# ---------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
      'timeout': 20,  # or some number of seconds
    }
    }
}

# ---------------------------
# Password validation
# ---------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ---------------------------
# Internationalization
# ---------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ---------------------------
# Default primary key field type
# ---------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATICFILES_DIRS = [
    BASE_DIR / "core" / "static",
]
USE_TZ = True
TIME_ZONE = 'Asia/Kolkata'

