# Generated by Django 4.2.23 on 2025-12-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
