# Generated by Django 5.2.7 on 2025-12-24 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_worksession_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(blank=True, null=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('login_lat', models.FloatField(blank=True, null=True)),
                ('login_lon', models.FloatField(blank=True, null=True)),
                ('login_address', models.TextField(blank=True, null=True)),
                ('logout_lat', models.FloatField(blank=True, null=True)),
                ('logout_lon', models.FloatField(blank=True, null=True)),
                ('logout_address', models.TextField(blank=True, null=True)),
                ('total_time', models.DurationField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
